vars:
  - target: src/maps/education/_data/view
stages:
  transform:
    cmd: PYTHONPATH=. python scripts/dfe/transform.py
    wdir: ../..
    deps:
      - scripts/dfe/transform.py
      - working/upstream/ks4_outcomes.csv
    outs:
      - ${target}/avg_att8_total.csv:
          cache: false
          persist: false
      - ${target}/avg_att8_girls.csv:
          cache: false
          persist: false
      - ${target}/avg_att8_boys.csv:
          cache: false
          persist: false
      - ${target}/avg_p8score_total.csv:
          cache: false
          persist: false
      - ${target}/avg_p8score_girls.csv:
          cache: false
          persist: false
      - ${target}/avg_p8score_boys.csv:
          cache: false
          persist: false