vars:
  - target: src/areas/maps/education/_data/view
stages:
  transform_ks4_outcomes:
    cmd: PYTHONPATH=. python scripts/dfe/transform_ks4_outcomes.py
    wdir: ../..
    deps:
      - scripts/dfe/transform_ks4_outcomes.py
      - working/upstream/ks4_outcomes.csv
    outs:
      - ${target}/ks4_outcomes.csv:
          cache: false
          persist: false
  transform_char_outcomes:
    cmd: PYTHONPATH=. python scripts/dfe/transform_char_outcomes.py
    wdir: ../..
    deps:
      - scripts/dfe/transform_char_outcomes.py
      - working/upstream/ks4_char_outcomes.csv
    outs:
      - ${target}/ks4_char_outcomes.csv:
          cache: false
          persist: false      
