vars:
  - target: src/maps/education/_data/view
stages:
  transform_ks4_outcomes:
    cmd: PYTHONPATH=. python scripts/dfe/transform_ks4_outcomes.py
    wdir: ../..
    deps:
      - scripts/dfe/transform_ks4_outcomes.py
      - working/upstream/ks4_outcomes.csv
    outs:
      - ${target}/ks4_outcomes/avg_att8/avg_att8_total.csv:
          cache: false
          persist: false
      - ${target}/ks4_outcomes/avg_att8/avg_att8_girls.csv:
          cache: false
          persist: false
      - ${target}/ks4_outcomes/avg_att8/avg_att8_boys.csv:
          cache: false
          persist: false
      - ${target}/ks4_outcomes/avg_p8/avg_p8score_total.csv:
          cache: false
          persist: false
      - ${target}/ks4_outcomes/avg_p8/avg_p8score_girls.csv:
          cache: false
          persist: false
      - ${target}/ks4_outcomes/avg_p8/avg_p8score_boys.csv:
          cache: false
          persist: false
  transform_char_outcomes:
    cmd: PYTHONPATH=. python scripts/dfe/transform_char_outcomes.py
    wdir: ../..
    deps:
      - scripts/dfe/transform_char_outcomes.py
      - working/upstream/ks4_char_outcomes.csv
    outs:
      - ${target}/ks4_char_outcomes/avg_att8/boys_total_char_outcomes.csv:
          cache: false
          persist: false      
      - ${target}/ks4_char_outcomes/avg_att8/girls_total_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_asian_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_black_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_mixed_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_other_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_unclassified_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/ethnicity_white_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/fsm_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/fsm_all_other_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/no_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/SEN_state_EHC_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/SEN_supp_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/any_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/no_identified_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/disadvantaged_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/disadvantaged_all_other_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/first_lang_english_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_att8/first_lang_not_english_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/boys_total_char_outcomes.csv:
          cache: false
          persist: false      
      - ${target}/ks4_char_outcomes/avg_p8/girls_total_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_asian_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_black_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_mixed_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_other_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_unclassified_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/ethnicity_white_ks4_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/fsm_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/fsm_all_other_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/no_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/SEN_state_EHC_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/SEN_supp_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/any_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/no_identified_SEN_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/disadvantaged_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/disadvantaged_all_other_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/first_lang_english_char_outcomes.csv:
          cache: false
          persist: false
      - ${target}/ks4_char_outcomes/avg_p8/first_lang_not_english_char_outcomes.csv:
          cache: false
          persist: false
        