vars:
  - top: ../..
stages:
  prepare:
    cmd:
      # Running multiple commands in a stage is perfectly fine.
      # Combined as they both use the same files and write to the same directory.
      - PYTHONPATH=. python3 scripts/international/prepare.py
      - perl scripts/international/transform.pl
    wdir: ${top}
    deps:
      - scripts/international/prepare.py
      - scripts/labour-market/config.py
      - scripts/international/transform.pl
      - working/upstream/oecd_lfs_by_sex_and_age.csv
    outs:
      # This will clear and track all the files in the output directory if the stage runs
      - src/areas/maps/international/_data/view/:
          cache: false