vars:
  - top: ../..
stages:
  prepare:
    cmd: PYTHONPATH=. python3 scripts/international/prepare.py
    wdir: ../..
    deps:
      - scripts/international/prepare.py
      - scripts/labour-market/config.py
      - working/upstream/oecd_lfs_by_sex_and_age.csv
    outs:
      - src/maps/international/_data/view:
          cache: false
  transform:
    cmd: perl scripts/international/transform.pl
    deps:
      - scripts/international/transform.pl
      - working/upstream/oecd_lfs_by_sex_and_age.csv
    outs:
      - src/maps/international/_data/view/oecd_lfs_grouped.csv:
          cache: false