vars:
  - top: ../..
stages:

  transform:
    cmd: PYTHONPATH=. python3 scripts/labour-market/transform.py
    wdir: ../..
    deps:
      - scripts/labour-market/transform.py
      - scripts/labour-market/config.py
      - working/upstream/lms.csv
    outs:
      - data/labour-market/monthly-rolling.csv:
          cache: false
          persist: false

  prepare:
    cmd: papermill prepare.ipynb ${top}/working/output/labour-market-prepare.ipynb
    deps:
      - prepare.ipynb
      - prepare.py
      - config.py
      - ${top}/scripts/util/
      - ${top}/data/labour-market/monthly-rolling.csv
      - ${top}/working/metadata.csv
    outs:
      - ${top}/src/_data/sources/labour-market/long_term_unemployed_last_3_years.csv:
          cache: false
          persist: false
      - ${top}/src/_data/sources/labour-market/long_term_unemployed_all_data.csv:
          cache: false
          persist: false
      - ${top}/src/_data/sources/labour-market/labour_market_status_last_3_years.csv:
          cache: false
          persist: false
      - ${top}/src/_data/sources/labour-market/labour_market_status_all_data.csv:
          cache: false
          persist: false
      - ${top}/src/_data/sources/labour-market/headlines.csv:
          cache: false
          persist: false
      - ${top}/src/dashboard/labour-market/_data/latest.json:
          cache: false
          persist: false
