stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/cpi/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/cpi/extract.py
    outs:
      - working/cpi/consumerpriceinflationdetailedreferencetables.xlsx:
          cache: false
          persist: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/cpi/transform.py
    wdir: ../..
    deps:
      - scripts/cpi/transform.py
      - scripts/util/date.py
      - working/MM23_data.csv
      - working/lookups/MM23_variable_lookup.csv
    outs:
      - data/cpi/transformed_cpi.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/cpi/prepare.py
    wdir: ../..
    deps:
      - scripts/cpi/prepare.py
      - data/cpi/transformed_cpi.csv
    outs:
      - src/_data/sources/cpi/cpi_barchart.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/cpi_linechart.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/metadata.json:
          cache: false
          persist: false
      - src/_data/sources/cpi/headlines.csv:
          cache: false 
          persist: false
  vis:
    cmd: PYTHONPATH=. python3 scripts/cpi/vis.py
    wdir: ../..
    deps:
      - scripts/cpi/vis.py
      - data/cpi/cpi_barchart.csv
      - data/cpi/cpi_all_category_bar_chart.csv
      - scripts/util/util.py
      # - src/dashboard/cpi/_data/sources/visualisations.yaml
    # outs:
    #   - src/dashboard/cpi/_data:
    #       cache: false
    #       persist: false