stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/cpi/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/cpi/extract.py
    outs:
      - working/cpi/consumerpriceinflationdetailedreferencetables.xlsx:
          cache: false
          persist: false
      
  transform:
    cmd: PYTHONPATH=. python3 scripts/cpi/transform.py
    wdir: ../..
    deps:
      - scripts/cpi/transform.py
      - scripts/util/date.py
      - working/cpi/consumerpriceinflationdetailedreferencetables.xlsx
      - working/lookups/MM23_variable_lookup.csv
    outs:
      - data/cpi/CPI.csv:
          cache: false
          persist: false
      - data/cpi/dates.json:
          cache: false
          persist: false