stages:
  transform:
    cmd: PYTHONPATH=. python3 scripts/cpi/transform.py
    wdir: ../..
    deps:
      - scripts/cpi/transform.py
      - scripts/util/date.py
      - working/upstream/mm23.csv
    outs:
      - data/cpi/transformed_cpi.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/cpi/prepare.py
    wdir: ../..
    deps:
      - scripts/cpi/prepare.py
      - data/cpi/transformed_cpi.csv
      - working/upstream/mm23-codes.csv
      - working/upstream/metadata.csv
    outs:
      - data/cpi/indicator.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/cpi_all_category_bar_chart.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/cpi_barchart.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/cpi_linechart.csv:
          cache: false
          persist: false
      - src/_data/sources/cpi/metadata.json:
          cache: false
          persist: false
      - src/_data/sources/cpi/headlines.csv:
          cache: false 
          persist: false
      - src/_data/sources/cpi/cpi_summary_barchart.csv:
          cache: false
          persist: false
  
  # NO LONGER NEEDED???
  # vis:
  #   cmd: PYTHONPATH=. python3 scripts/cpi/vis.py
  #   wdir: ../..
  #   deps:
  #     - scripts/cpi/vis.py
  #     - src/_data/sources/cpi/cpi_barchart.csv
  #     - src/_data/sources/cpi/cpi_all_category_bar_chart.csv
  #     - scripts/util/util.py
    # outs:
    #   - src/dashboard/cpi/_data/visualisation:
    #       cache: false
    #       persist: false