stages:
  transform:
    cmd: PYTHONPATH=. python scripts/education/transform.py
    wdir: ../..
    deps:
      - scripts/education/transform.py
      - working/upstream/education.csv
    outs:
      - src/maps/education/_data/view:
          cache: false
          persist: false
