stages:
  transform:
    cmd: PYTHONPATH=. python scripts/maps/transform.py
    wdir: ../..
    deps:
      - scripts/maps/transform.py
      - working/upstream/labour-market_most_recent_by_pcon.csv
      - working/upstream/claimants-per-population-latest.csv
      - working/upstream/census-employment-status.csv
    outs:
      - src/areas/maps/employment/_data/view:
          cache: false
          persist: false
