stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/vacancies/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/vacancies/extract.py
    outs: 
      - working/vacancies/vacancies_by_sector.csv:
          cache: false
          persist: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/vacancies/transform.py
    wdir: ../..
    deps:
      - scripts/vacancies/transform.py
      - working/upstream/lms.csv
      - working/upstream/lms-codes.csv
    outs:
      - data/vacancies/vacancies_edd.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/vacancies/prepare.py
    wdir: ../..
    deps:
      - scripts/vacancies/prepare.py
      - working/vacancies/vacancies_by_sector.csv
      - data/vacancies/vacancies_edd.csv
      - working/metadata.csv
    outs:
      - src/_data/sources/vacancies/:
          cache: false
          persist: false


