vars:
  - top: ../..
stages:
  transform:
    cmd: papermill --no-progress-bar transform.ipynb ${top}/working/output/vacancies-transform.ipynb
    deps:
      - transform.ipynb
      - ${top}/working/upstream/unem.csv
      - ${top}/working/upstream/unem-codes.csv
    outs:
      - ${top}/data/vacancies/vacancies_by_date.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/vacancies/prepare.py
    wdir: ../..
    deps:
      - scripts/vacancies/prepare.py
      - scripts/util/metadata.py
      - data/vacancies/vacancies_by_date.csv
      - working/upstream/vacancies-growth-by-sector.csv
      - working/upstream/metadata.csv
    outs:
      - src/_data/sources/vacancies/:
          cache: false
          persist: false


