stages:
  transform:
    cmd: PYTHONPATH=. python3 scripts/vacancies/transform.py
    wdir: ../..
    deps:
      - scripts/vacancies/transform.py
      - working/upstream/lms.csv
      - working/upstream/lms-codes.csv
    outs:
      - data/vacancies/vacancies_by_date.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/vacancies/prepare.py
    wdir: ../..
    deps:
      - scripts/vacancies/prepare.py
      - scripts/util/metadata.py
      - data/vacancies/vacancies_by_date.csv
      - working/upstream/vacancies-growth-by-sector.csv
    outs:
      - src/_data/sources/vacancies/:
          cache: false
          persist: false


