stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/qlfs/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/qlfs/extract.py
    outs:
      - working/qlfs/a06latest.xls:
          cache: false
          persist: false
      - working/qlfs/unem01latest.xls:
          cache: false
          persist: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/qlfs/transform.py
    wdir: ../..
    deps:
      - scripts/qlfs/transform.py
      - scripts/util/date.py
      - working/qlfs/a06latest.xls
      - working/qlfs/unem01latest.xls
      - working/lookups/lms_lookups.csv
    outs:
      - data/qlfs/long_term_unemployed.csv:
          cache: false
          persist: false
      - data/qlfs/not_in_education.csv:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/qlfs/prepare.py
    wdir: ../..
    deps:
      - scripts/qlfs/prepare.py
      - scripts/util/file.py
      - data/qlfs/long_term_unemployed.csv
      - data/qlfs/not_in_education.csv
    outs:
      - src/_data/sources/qlfs/headlines.csv:
          cache: false
          persist: false
      - src/_data/sources/qlfs/long_term_unemployed_last_3_years.csv:
          cache: false
          persist: false
      - src/_data/sources/qlfs/long_term_unemployed_all_data.csv:
          cache: false
          persist: false
      - src/_data/sources/qlfs/not_in_education_last_3_years.csv:
          cache: false
          persist: false
      - src/_data/sources/qlfs/not_in_education_all_data.csv:
          cache: false
          persist: false
