stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/qlfs/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/qlfs/extract.py
    outs:
      - working/qlfs/a06latest.xls:
          cache: false
          persist: false
      - working/qlfs/unem01latest.xls:
          cache: false
          persist: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/qlfs/transform.py
    wdir: ../..
    deps:
      - scripts/qlfs/transform.py
      - scripts/util/date.py
      - working/qlfs/a06latest.xls
      - working/qlfs/unem01latest.xls
      - working/lookups/lms_lookups.csv
    outs:
      - data/qlfs/16_to_24_long_term_unemployed.csv:
          cache: false
          persist: false
      - data/qlfs/16_to_24_not_in_education.csv:
          cache: false
          persist: false
