stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/qlfs/extract.py
    always_changed: true
    wdir: ../..
    deps:
      - scripts/qlfs/extract.py
    outs:
      - working/qlfs/a06latest.xls:
          cache: false
          persist: false
      - working/qlfs/unem01latest.xls:
          cache: false
          persist: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/qlfs/transform.py
    wdir: ../..
    deps:
      - scripts/qlfs/transform.py
      - scripts/util/date.py
      - working/qlfs/a06latest.xls
      - working/qlfs/unem01latest.xls
    outs:
      - data/qlfs/metadata.json:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/qlfs/prepare.py
    wdir: ../..
    deps:
      - scripts/qlfs/prepare.py
      - scripts/util/file.py
      - data/qlfs/metadata.json
    outs:
<<<<<<< HEAD
      - src/dashboard/labour-market/_data/dates.json:
=======
      - src/_data/sources/qlfs/headlines.csv:
          cache: false
          persist: false
      - src/dashboard/labour-market/_data/latest.json:
>>>>>>> parent of 74cfb67 (Merge branch 'main' of https://github.com/open-innovations/yff-data)
          cache: false
          persist: false
