vars:
  - top: ../..
stages:
  transform:
    cmd: papermill transform.ipynb ${top}/working/output/neet-transform.ipynb
    deps:
      - transform.ipynb
      - ${top}/working/upstream/neet.csv
      - ${top}/working/upstream/metadata.csv
    outs:
      - ${top}/data/neet/neet.csv:
          cache: false
          persist: false
      - ${top}/data/neet/metadata.json:
          cache: false
          persist: false
  prepare:
    cmd: PYTHONPATH=. python scripts/neet/prepare.py
    wdir: ../..
    deps:
      - scripts/neet/prepare.py
      - scripts/util/date.py
      - scripts/util/file.py
      - data/neet/neet.csv
    outs:
      - src/_data/sources/neet/neet_last_3_years.csv:
          cache: false
          persist: false
      - src/_data/sources/neet/neet_all_data.csv:
          cache: false
          persist: false
      - src/_data/sources/neet/headlines.csv:
          cache: false
          persist: false
      - src/dashboard/neet/_data/latest.json:
          cache: false
          persist: false
